
export const GridItems = [
    {   Title: "TrackMyTime Story>Chart - GridChart",
        webPartScenario: { results: ['Dev','Team','Corp']},
        showEarlyAccess:true,
        parentListTitle: 'TrackMyTime',
        parentListWeb: '/sites/Templates/Tmt/',

        monthGap: "1",
        squareCustom: "transparent,#ebedf0,#c6e48b,#7bc96f,#196127",
        cellColor: "green",
        scaleMethod: "blink",

        dateColumn:'StartTime',
        dropDownColumns:'+Story,+>Chapter,+User/Title',
        searchColumns:'',
        metaColumns: '',
        valueColumn:'Hours',
        valueOperator:'Sum',
        valueType:'Number',

        enableSearch:true,
        fetchCount:2000,
        fetchCountMobile:2000,
        minDataDownload:true,
        restFilter:'',
    },
    {   Title: "Documents - GridChart",
        webPartScenario: { results: ['Dev','Team','Corp']},
        showEarlyAccess:true,
        parentListTitle: 'Documents',
        parentListWeb: '',

        monthGap: "1",
        squareCustom: "transparent,#ebedf0,#c6e48b,#7bc96f,#196127",
        cellColor: "green",
        scaleMethod: "blink",

        dateColumn:'Modified',
        dropDownColumns:'+Author/Title,+Editor/Title',
        searchColumns:'',
        metaColumns: '',
        valueColumn:'Id',
        valueOperator:'Count',
        valueType:'Number',

        enableSearch:true,
        fetchCount:2000,
        fetchCountMobile:2000,
        minDataDownload:true,
        restFilter:'',
    },
    {   Title: "Turnover - GridChart",
        webPartScenario: { results: ['Dev','Team','Corp']},
        showEarlyAccess:true,
        parentListTitle: 'ACH Turnover',
        parentListWeb: '/sites/WebpartDev',

        monthGap: "1",
        squareCustom: "transparent,#ebedf0,#c6e48b,#7bc96f,#196127",
        cellColor: "green",
        scaleMethod: "blink",

        dateColumn:'zzzDate1',
        dropDownColumns:'+zzzChoice1,+zzzItemCategory',
        searchColumns:'',
        metaColumns: '',
        valueColumn:'zzzNumber05',
        valueOperator:'Sum',
        valueType:'Number',

        enableSearch:true,
        fetchCount:5000,
        fetchCountMobile:2000,
        minDataDownload:true,
        restFilter:'',
    },
    {   Title: "TTPGrid - GridChart",
        webPartScenario: { results: ['Dev','Team','Corp']},
        showEarlyAccess:true,
        parentListTitle: 'ttpGrid',
        parentListWeb: '/sites/Templates/Brasov',

        monthGap: "",
        squareCustom: "black,pink,red,pink,yellow",
        cellColor: "green",
        scaleMethod: "blink",

        dateColumn:'TheDate',
        dropDownColumns:'+Author/Title,+Message',
        searchColumns:'',
        metaColumns: '',
        valueColumn:'Id',
        valueOperator:'Count',
        valueType:'Number',

        enableSearch:true,
        fetchCount:5000,
        fetchCountMobile:2000,
        minDataDownload:true,
        restFilter:'',
    }
];